#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt', '>= 1.9.2'
cookbook 'sudo', '>= 2.0.4'
cookbook 'user', '>= 0.3.0'

# cookbook 'vim', '>= 1.0.2'
cookbook 'emacs', '>= 0.9.0'

# cookbook 'mysql', '>= 3.0.0'
# cookbook 'apache2', '>= 1.0.0'

# cookbook 'java', '>= 1.10.0'
# cookbook 'scala', '>= 0.0.1'
# cookbook 'python', '>= 1.2.2'
# cookbook 'leiningen', '>= 0.2.0'
# cookbook 'chef-golang', '>= 1.0.1'

# cookbook 'zsh', '>= 1.0.0'
# cookbook 'oh-my-zsh-solo', '>= 0.3.3'

cookbook 'htop', '>= 1.0.0'
cookbook 'curl', '>= 1.1.0'

# cookbook 'hostname', '>= 0.0.4'
# cookbook 'openvpn', '>= 1.1.0'
# cookbook 'ssh_known_hosts', '>= 0.7.4'

# cookbook 'ufw', '>= 0.6.1'
# cookbook 'udev', '>= 0.2.0'
# cookbook 'iftop', '>= 0.0.1'
# cookbook 'vnstat', '>= 0.0.1'
# cookbook 'iptables', '>= 0.12.0'
# cookbook 'dnsimple', '>= 0.5.0'

# cookbook 'nmap', '>= 0.1.0'
# cookbook 'traceroute', '>= 1.0.0'

# cookbook 'nginx', '>= 1.4.0'
# cookbook 'memcached', '>= 1.3.0'

cookbook 'git', '>= 2.5.0'
# cookbook 'mercurial', '>= 1.1.4'
# cookbook 'subversion', '>= 1.0.2'

# cookbook 'maven', '>= 0.16.2'
cookbook 'build-essential', '>= 1.4.0'

# cookbook 'docker',
#   :git => 'https://github.com/thoward/docker-cookbook'

# cookbook 'chef-client'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
